# Generated by Django 4.0.4 on 2022-06-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
